/******************************************************************************
* File Name:	main.c
*
* Description:	Main file of the IMR Robot Control
* 				see doctrings or README.md for details.
*
* Related Document: See README.md
* 
* Authors: 		Schmidt Michael
* 				Granig Jonas
* 				Detzel Samuel
*
*******************************************************************************
*
* Copyright (c) 2024, Infineon Technologies AG
* All rights reserved.
*
* Boost Software License - Version 1.0 - August 17th, 2003
*
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
*
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*****************************************************************************/

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

#include "IMR_CAN_GLOBAL.h"
#include "cybsp.h"
#include "cy_utils.h"
#include "Libraries/CAN/IMR_CAN.h"
#include "Libraries/IMRRC.h"
#include "Libraries/IMRMecanum.h"
#include "Libraries/ADCinput/IMRADCinput.h"

/* Interrupt for LED bar-graph.
 * Note CCU40_2_IRQn is already used by TIMER_TIMEOUT */
#define MTRSPEED_LED_PERIOD_MATCH_EVENT_IRQN		CCU40_0_IRQn
#define MTRSPEED_LED_PERIOD_MATCH_EVENT_HANDLER		IRQ_Hdlr_44
#if POTI_INPUT
#define MAX_SPEED_VAL	16380.0 // (4095*8/2) = scaled ADC value
#else
#define MAX_SPEED_VAL	32768.0 // (INT16)
#endif

/*****************************************************************************
 * Global variables
*****************************************************************************/
uint8_t RC_failsafe = 0;
int16_t remote_v[3] = { 0 , 0 , 0 }; // Trajectory values from RC
RCinput_t RemoteControl_IN;
int16_t wS[4]; 
int16_t motorOutput[4] = { 0 };
extern float encoderSpeed[4];

#if POTI_INPUT //potentiometer for speed control
bool zeropass = false;
int16_t poti_speed_left, poti_speed_right;
#endif

uint8_t* git_commit_hash = (uint8_t*)GIT_COMMIT_HASH;

/******************************************************************************
 * CANStatus_LED:
 * Set the blue LED on board to blink when the CAN transmit is successful
 *****************************************************************************/
void CANStatus_LED(CAN_STATUS_t status)
{
	if(status == CAN_SUCCESS){
		XMC_GPIO_ToggleOutput(LED_Blue_PORT,LED_Blue_PIN); // LED blinks
	}
	else XMC_GPIO_SetOutputHigh(LED_Blue_PORT,LED_Blue_PIN); // LED OFF
}

/******************************************************************************
 * Timer Interrupt
 * - Called every 100ms to send current wheels' speed to the Motor Control
 *****************************************************************************/
void TIMER_TIMEOUT_PERIOD_MATCH_EVENT_HANDLER(void)
{
	uint8_t CANBuffer[6];
	CAN_STATUS_t sendStatus;

#if POTI_INPUT
	if(!zeropass && abs(poti_speed_left) < 100 &&
			abs(poti_speed_right) < 100) {
		zeropass = true;
	}
	// require both potis to be close to 0 before first motor movement
	if (zeropass){
		wS[0] = poti_speed_left;
		wS[1] = poti_speed_right;
		wS[2] = poti_speed_left;
		wS[3] = poti_speed_right;
	}
#endif
	applyFIRFilter(wS, motorOutput);

	// send required motor speed to all 4 IMD701A boards
	for (int i = 0; i < 4; i++) {
		CANBuffer[0] = (uint8_t)(((motorOutput[i] & 0xFF00) >> 8) & 0xFF);
		CANBuffer[1] = (uint8_t) ((motorOutput[i]) & 0xFF);
		sendStatus = CAN_TX_Request(MOT_FL_SPEED_COMMAND + i, CANBuffer, 2);
		CANStatus_LED(sendStatus);
	}
	memset(wS,0,8);

	if(Trajectory_ttl > 0U) {
		// processing the trajectory CAN command
		if((RC_failsafe > 0 && RemoteControl_IN.Switch_SD == 1) ||
				RC_failsafe == 0){
			int16_t vel[3];	// Robot target velocity
			can2Vel(Trajectory_data, vel);
			inverseKinematics(vel, wS);
		}
		Trajectory_ttl--;
	}
	// Sending Odometry
	int16_t v_odo[3]; // Odometry estimate
	estimateOdometry(encoderSpeed, v_odo);
	CANBuffer[0] = (uint8_t) ((v_odo[0] & 0xFF00) >> 8);
	CANBuffer[1] = (uint8_t) (v_odo[0] & 0xFF);
	CANBuffer[2] = (uint8_t) ((v_odo[1] & 0xFF00) >> 8);
	CANBuffer[3] = (uint8_t) (v_odo[1] & 0xFF);
	CANBuffer[4] = (uint8_t) ((v_odo[2] & 0xFF00) >> 8);
	CANBuffer[5] = (uint8_t) (v_odo[2] & 0xFF);
	sendStatus = CAN_TX_Request(ROBOT_ODOMETRY_ESTIMATE, CANBuffer, 6);
	CANStatus_LED(sendStatus);
}

/******************************************************************************
 * LED control interrupt with potentiometer's input
 * - Called every 1sec to send current wheels' speed to the LED boards
 *****************************************************************************/
void MTRSPEED_LED_PERIOD_MATCH_EVENT_HANDLER(void) {
	int16_t mtr_speed[4];
	// scale the motorOutput from 0 - 16380 values to 0 - 100 (%)
	// +1 is to ensure that max. reading reaches 100%
	for (int i = 0; i < 4; i++) {
		mtr_speed[i] = (int16_t)
					   ((float)motorOutput[i] / (MAX_SPEED_VAL / 100.0));
		if (mtr_speed[i] < 0) mtr_speed[i] = mtr_speed[i] - 1;
		else mtr_speed[i] = mtr_speed[i] + 1;
	}
#if (BARGRAPH_ENABLED && !SPEED_LED_BY_PSC3)
#if (BARGRAPH_CONFIG == 0)
	barGraph(mtr_speed[0], mtr_speed[1]);
#elif (BARGRAPH_CONFIG == 1)
	barGraph(mtr_speed[0], mtr_speed[1]);
	barGraph(mtr_speed[2], mtr_speed[3]);
#elif (BARGRAPH_CONFIG == 2)
	ledSnake_shortBoard(mtr_speed[0], mtr_speed[1]);
#endif
#endif
}

/******************************************************************************
 * MAIN METHOD
 *****************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }
	CAN_Initialize();

	/* Start timers and enable interrupt for LED timer */
#if (BARGRAPH_ENABLED && !SPEED_LED_BY_PSC3)
	NVIC_EnableIRQ(MTRSPEED_LED_PERIOD_MATCH_EVENT_IRQN);
    XMC_CCU4_SLICE_StartTimer(MTRSPEED_LED_HW);
#endif
    XMC_CCU4_SLICE_StartTimer(TIMER_TIMEOUT_HW);

    XMC_GPIO_SetOutputHigh(LED_Blue_PORT,LED_Blue_PIN); 	// LED OFF
	XMC_GPIO_SetOutputHigh(LED_Green_PORT,LED_Green_PIN);	// LED OFF
	XMC_UART_CH_EnableInputInversion(SBUS_UART_HW, XMC_UART_CH_INPUT_RXD);

	if(false)  // enable/disable for static LED display.
	{
		RCinput_t input;
		input.Switch_SB = 1; // select color
		input.Switch_SA = 1; // pulsing
		readLEDinput(input);
	}
#if POTI_INPUT
	ADC_Initialize();
#endif
	// Send out commit hash of currently flashed software
	CAN_TX_Request(COMMIT_HASH, (uint8_t*)git_commit_hash, 7);

    // LOOP
    while(1U)
    {
	    if(SBUSRX_Parse() && !BMS_PowerReduced){
		    RemoteControl_IN = Process_RC_Inputs(sbus_data);
			
		    if(sbus_data.failsafe == false)
		    	RC_failsafe = RC_TIME_TO_LIVE;

		    // can be commented if LED control is not to be used
		    // via RemoteControl
		    readLEDinput(RemoteControl_IN);

		    memset(remote_v,0,6);
		    // Switch D Must be enabled (Dead man switch)
		    if(RemoteControl_IN.Switch_SD == 3 &&
		    		sbus_data.lost_frame == false) {

			    remote_v[0] =  RemoteControl_IN.RightStick_UpDown*10922/100;
			    remote_v[1] = -RemoteControl_IN.RightStick_LeftRight*10922/100;
			    remote_v[2] =  RemoteControl_IN.LeftStick_LeftRight*5215/100*2;

			    if(remote_v[0] || remote_v[1] || remote_v[2]) {
				      inverseKinematics(remote_v, wS);
			    }
		    }
			XMC_GPIO_SetOutputLow(LED_Green_PORT, LED_Green_PIN);
	    }
	    // Green OnBoard LED will be off
	    // if no RC commands are received after TTL.
	    if(RC_failsafe != 0) {
		    RC_failsafe--; 
		    XMC_GPIO_SetOutputLow(LED_Green_PORT, LED_Green_PIN);
	    }
	    else {
			XMC_GPIO_SetOutputHigh(LED_Green_PORT, LED_Green_PIN);
	    }
	    memset(remote_v,0,6);
    }
}

/* [] END OF FILE */
