/******************************************************************************
 * (c) (2024), Cypress Semiconductor Corporation (an Infineon company) or
 * an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 * This software, including source code, documentation and related
 * materials ("Software") is owned by Cypress Semiconductor Corporation
 * or one of its affiliates ("Cypress") and is protected by and subject to
 * worldwide patent protection (United States and foreign),
 * United States copyright laws and international treaty provisions.
 * Therefore, you may use this Software only as provided in the license
 * agreement accompanying the software package from which you
 * obtained this Software ("EULA").
 * If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 * non-transferable license to copy, modify, and compile the Software
 * source code solely for use in connection with Cypress's
 * integrated circuit products.  Any reproduction, modification, translation,
 * compilation, or representation of this Software except as specified
 * above is prohibited without the express written permission of Cypress.
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
 * reserves the right to make changes to the Software without notice. Cypress
 * does not assume any liability arising out of the application or use of the
 * Software or any product or circuit described in the Software. Cypress does
 * not authorize its products for use in any products where a malfunction or
 * failure of the Cypress product may reasonably be expected to result in
 * significant property damage, injury or death ("High Risk Product").
 * By including Cypress's product in a High Risk Product, the manufacturer
 * of such system or application assumes all risk of such use and in doing so
 * agrees to indemnify Cypress against all liability.
******************************************************************************/

#include "IMRADCinput.h"

#if POTI_INPUT
#include <stdint.h>

/******************************************************************************
 * Interrupt handler for VADC SR2.
 *
 * This function is the interrupt service routine (ISR) for handling
 * interrupts generated by the VADC (Versatile Analog-to-Digital Converter)
 * SR2 (Service Request 2). It is triggered by conversion results from
 * both Channels 0 and 1
 *
 * Ensure that the interrupt is properly configured and enabled
 * in the system to trigger this handler.
 * Ensure that this function resolves as quickly as possible,
 * to prevent timing issues such as blocking all other executions on the chip.
 *****************************************************************************/
void VADC_SR2_INTERRUPT_HANDLER(void)
{
    // Read the VADC results and update the motor speeds
	// Convert from unsigned 12 bit VADC to 16 bit signed and
	// divide by 2 to adjust speed range (i.e. 0 to ~286.4 RPM)
	int16_t speed_left = XMC_VADC_GROUP_GetResult(VADC_GROUP_HW, 1U) * (1 << 2);
	speed_left = XMC_GPIO_GetInput(DIR_LEFT_PORT, DIR_LEFT_PIN) ?
			-speed_left : speed_left;

	int16_t speed_right = XMC_VADC_GROUP_GetResult(VADC_GROUP_HW, 0U) * (1 << 2);
	speed_right = XMC_GPIO_GetInput(DIR_RIGHT_PORT, DIR_RIGHT_PIN) ?
			speed_right : -speed_right;

	// Separate call to global variable to speed up above calculations
	// (otherwise, this function is too slow)
	poti_speed_left = speed_left;
	poti_speed_right = speed_right;
}

/******************************************************************************
 * Initialize the VADC
 *****************************************************************************/
void ADC_Initialize(void)
{
	/* Add all channels into the Background Request
	 * Source Channel Select Register*/
	XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, VADC_GROUP_NUM, 0U);
	XMC_VADC_GLOBAL_BackgroundAddChannelToSequence(VADC, VADC_GROUP_NUM, 1U);
	/* Enable Background Continuous Scan Request source IRQ */
	NVIC_EnableIRQ(VADC_SR2_IRQN);
	/* Generate a load event to start background request source
	 * continuous conversion*/
	XMC_VADC_GLOBAL_BackgroundTriggerConversion(VADC);
}

#endif
